/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/analysis/deviation-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Настройки D1–D10 */
        get: operations["list_rules_api_v1_analysis_deviation_rules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/deviation-rules/{code}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Настройка одного кода */
        get: operations["get_rule_api_v1_analysis_deviation_rules__code__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить пороги, серьёзность или тексты правила
         * @description Действует со следующего прогона. `X-Actor` — кто правит, попадает в журнал.
         */
        patch: operations["update_rule_api_v1_analysis_deviation_rules__code__patch"];
        trace?: never;
    };
    "/api/v1/analysis/deviations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Лента отклонений
         * @description Повторяющийся параметр — несколько значений: `?severity=HIGH&severity=MEDIUM`. `verdict` — `CONFIRMED` / `REJECTED`, вердикт оператора независимо от статуса: закрытое с вердиктом остаётся `RESOLVED`. `from`/`to` — эпизоды, пересекающиеся с `[from, to)`. `sort` — `last_seen_at`, `first_seen_at` или `severity`, минус — по убыванию; по умолчанию `-last_seen_at`.
         */
        get: operations["list_deviations_api_v1_analysis_deviations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/deviations/{deviation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка отклонения */
        get: operations["get_deviation_api_v1_analysis_deviations__deviation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Вердикт оператора: подтвердить или пометить ложным
         * @description `X-Actor` — кто вынес вердикт (по-русски — в URL-кодировке). `REJECTED` не открывается заново, пока условие держится непрерывно.
         */
        patch: operations["set_verdict_api_v1_analysis_deviations__deviation_id__patch"];
        trace?: never;
    };
    "/api/v1/analysis/deviations/{deviation_id}/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Полное объяснение: правило, сессии эпизода, снимки */
        get: operations["explain_deviation_api_v1_analysis_deviations__deviation_id__explain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/objects/{object_id}/equipment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Загрузка техники по дням и классам (F10)
         * @description Фильтр по местным датам — полуинтервал `[from, to)`.
         */
        get: operations["get_equipment_api_v1_analysis_objects__object_id__equipment_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/objects/{object_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Прогресс, SPI и прогноз по этапам — данные для Ганта */
        get: operations["get_progress_api_v1_analysis_objects__object_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/objects/{object_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Сводный статус объекта для дашборда */
        get: operations["get_status_api_v1_analysis_objects__object_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Отчёты объекта, новые сверху */
        get: operations["list_reports_api_v1_analysis_reports_get"];
        put?: never;
        /**
         * Сформировать PDF-отчёт за период
         * @description Период — местные дни календаря объекта включительно. Формирование синхронное: ответ приходит с готовой ссылкой. Отчёт того же периода, сформированный в тот же день, заменяется.
         */
        post: operations["create_report_api_v1_analysis_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/reports/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ссылка на готовый отчёт
         * @description `key` — ключ из списка, вида `{object_id}/{дата}T{ЧЧММСС}-{начало}_{конец}.pdf`.
         */
        get: operations["get_report_api_v1_analysis_reports__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Запустить прогон или подать сигнал «пересчитай»
         * @description Без `wait` прогон идёт в фоне, ответ 202. С `wait=true` — 200 и результат прогона, как у `GET /runs/{id}`; ошибка прогона приходит конвертом ошибки. Если по объекту прогон уже идёт, сигнал схлопывается с ним (`coalesced: true`, номер идущего), а по его окончании запускается ровно один новый. `wait=true` в этом случае ждёт, пока прогоны по объекту закончатся, и отдаёт последний; не дождался — 202.
         */
        post: operations["create_run_api_v1_analysis_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Результат прогона */
        get: operations["get_run_api_v1_analysis_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Резюме за период: нейросеть с проверкой чисел или шаблон
         * @description Тот же контекст и период по умолчанию, что у `POST /reports`. Текст нейросети показывается, только если каждое его число есть в фактах, а каждая ссылка — ID отклонения; иначе резюме шаблонное, а причина — в `llm_rejected`.
         */
        post: operations["create_summary_api_v1_analysis_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Процесс жив */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Готов обслуживать запросы */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActivityDay */
        ActivityDay: {
            /** Activity Index */
            activity_index: number | null;
            /** Blind Sessions */
            blind_sessions: number;
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Sessions Total */
            sessions_total: number;
            /** Sessions Working */
            sessions_working: number;
        };
        /**
         * DeviationRead
         * @description Карточка: текст для человека, числа для проверки, снимки-доказательства.
         */
        DeviationRead: {
            /** Area */
            area: string | null;
            /** Code */
            code: string;
            /** Equipment Class */
            equipment_class: string | null;
            /** Evidence */
            evidence: Record<string, never>[];
            /** Facts */
            facts: Record<string, never>;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Message */
            message: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Occurrences */
            occurrences: number;
            /** Rule Ref */
            rule_ref: Record<string, never>;
            /** Session Id */
            session_id: string | null;
            /** Severity */
            severity: string;
            /** Stage Id */
            stage_id: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /**
             * Verdict
             * @description CONFIRMED / REJECTED — вердикт оператора; у закрытого статус остаётся RESOLVED
             */
            verdict: string | null;
            /** Verdict At */
            verdict_at: string | null;
            /** Verdict By */
            verdict_by: string | null;
            /** Verdict Comment */
            verdict_comment: string | null;
        };
        /** DeviationRuleRead */
        DeviationRuleRead: {
            /** Code */
            code: string;
            /** Enabled */
            enabled: boolean;
            /** Message Template */
            message_template: string;
            /** Params */
            params: Record<string, never>;
            /**
             * Predicate
             * @description Имя предиката из реестра; правится только в коде
             */
            predicate: string;
            /** Severity */
            severity: string;
            /** Title Template */
            title_template: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * DeviationRuleUpdate
         * @description Частичная правка: передаются только меняемые поля.
         */
        DeviationRuleUpdate: {
            /** Enabled */
            enabled?: boolean | null;
            /** Message Template */
            message_template?: string | null;
            /**
             * Params
             * @description Сливается с текущими параметрами по ключам; ключ со значением null удаляется
             * @example {
             *       "min_sessions": 3
             *     }
             */
            params?: Record<string, never> | null;
            /**
             * Severity
             * @example HIGH
             */
            severity?: string | null;
            /** Title Template */
            title_template?: string | null;
        };
        /** DeviationVerdict */
        DeviationVerdict: {
            /** Comment */
            comment?: string | null;
            /**
             * Status
             * @description CONFIRMED или REJECTED
             * @example REJECTED
             */
            status: string;
        };
        /** EquipmentDay */
        EquipmentDay: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Equipment Class */
            equipment_class: string;
            /** Max Count */
            max_count: number;
            /** Sessions Seen */
            sessions_seen: number;
        };
        /** EquipmentRead */
        EquipmentRead: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Items */
            items: components["schemas"]["EquipmentDay"][];
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
        };
        /** EvidenceRead */
        EvidenceRead: {
            /** Detection Ids */
            detection_ids: string[];
            /**
             * Image Id
             * Format: uuid
             */
            image_id: string;
            /** Image Path */
            image_path: string;
        };
        /** ExplainRead */
        ExplainRead: {
            deviation: components["schemas"]["DeviationRead"];
            /** Evidence */
            evidence: components["schemas"]["EvidenceRead"][];
            /** @description Действующая настройка правила */
            rule: components["schemas"]["DeviationRuleRead"] | null;
            /**
             * Sessions
             * @description Сессии эпизода с фактами участка; null — site-service не ответил
             */
            sessions: Record<string, never>[] | null;
            /**
             * Sessions Truncated
             * @description Показаны только последние сессии эпизода
             */
            sessions_truncated: boolean;
            /** Sessions Unavailable Reason */
            sessions_unavailable_reason: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ObjectStatusRead */
        ObjectStatusRead: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Blind Areas
             * @description Участки, не видимые в последней рабочей сессии
             */
            blind_areas: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Confidence */
            confidence: string;
            /** Delay Days */
            delay_days: number | null;
            /**
             * Deviations
             * @description Открытые отклонения по серьёзности
             */
            deviations: {
                [key: string]: number;
            };
            /**
             * Facts
             * @description Числа статуса: дни наблюдений, видимость
             */
            facts: Record<string, never>;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Spi */
            spi: number | null;
            /**
             * Stages
             * @description Этапы по статусам и `total`
             */
            stages: {
                [key: string]: number;
            };
            /** Stages At Risk */
            stages_at_risk: Record<string, never>[];
            /** Status */
            status: string;
        };
        /** Page[DeviationRead] */
        Page_DeviationRead_: {
            /** Items */
            items: components["schemas"]["DeviationRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[DeviationRuleRead] */
        Page_DeviationRuleRead_: {
            /** Items */
            items: components["schemas"]["DeviationRuleRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[ReportRead] */
        Page_ReportRead_: {
            /** Items */
            items: components["schemas"]["ReportRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /**
         * ProgressRead
         * @description Названия и плановые даты этапов — в plan-service; здесь только факт и прогноз.
         */
        ProgressRead: {
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Stages */
            stages: components["schemas"]["StageProgress"][];
        };
        /** ReportCreate */
        ReportCreate: {
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Period From
             * @description Первый местный день периода; по умолчанию — неделя до конца
             */
            period_from?: string | null;
            /**
             * Period To
             * @description Последний местный день включительно; по умолчанию — день as_of
             */
            period_to?: string | null;
        };
        /** ReportCreated */
        ReportCreated: {
            /**
             * As Of
             * Format: date-time
             * @description Момент анализа, чьи выводы вошли в отчёт
             */
            as_of: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Evidence Images
             * @description Снимков-доказательств вставлено
             */
            evidence_images: number;
            /**
             * Evidence Missing
             * @description Снимков не вставлено; причины — в разделе «Ограничения»
             */
            evidence_missing: number;
            /**
             * Generated On
             * Format: date
             * @description Местный день формирования — часть ключа
             */
            generated_on: string;
            /**
             * Key
             * @description Ключ файла в бакете `reports`; им же читается ссылка
             */
            key: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Period From
             * Format: date
             */
            period_from: string;
            /**
             * Period To
             * Format: date
             */
            period_to: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Summary Generated By
             * @description `TEMPLATE` или `LLM` — источник резюме
             */
            summary_generated_by: string;
            /**
             * Url
             * @description Presigned-ссылка на S3_PUBLIC_ENDPOINT; живёт S3_PRESIGN_TTL_S
             */
            url: string;
        };
        /** ReportRead */
        ReportRead: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Generated On
             * Format: date
             * @description Местный день формирования — часть ключа
             */
            generated_on: string;
            /**
             * Key
             * @description Ключ файла в бакете `reports`; им же читается ссылка
             */
            key: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Period From
             * Format: date
             */
            period_from: string;
            /**
             * Period To
             * Format: date
             */
            period_to: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Url
             * @description Presigned-ссылка на S3_PUBLIC_ENDPOINT; живёт S3_PRESIGN_TTL_S
             */
            url: string;
        };
        /** RunAccepted */
        RunAccepted: {
            /** Coalesced */
            coalesced: boolean;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Status */
            status: string;
        };
        /** RunCreate */
        RunCreate: {
            /**
             * As Of
             * @description Момент, на который считается анализ. Пусто — конец последней сессии с фактами, а без фактов — момент запуска
             */
            as_of?: string | null;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Triggered By
             * @default MANUAL
             * @example FACTS_UPDATED
             */
            triggered_by: string;
        };
        /** RunRead */
        RunRead: {
            /** As Of */
            as_of: string | null;
            /** Error */
            error: Record<string, never> | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Plan Version */
            plan_version: number | null;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Stats */
            stats: Record<string, never>;
            /** Status */
            status: string;
            /** Triggered By */
            triggered_by: string;
            /** Zones Version */
            zones_version: number | null;
        };
        /** StageProgress */
        StageProgress: {
            /** Activity */
            activity: components["schemas"]["ActivityDay"][];
            /** Actual Start */
            actual_start: string | null;
            /** Confidence */
            confidence: string;
            /** Delay Days */
            delay_days: number | null;
            /** Effective Days */
            effective_days: number;
            /** Facts */
            facts: Record<string, never>;
            /** Forecast End */
            forecast_end: string | null;
            /** Last Activity At */
            last_activity_at: string | null;
            /** Planned Progress */
            planned_progress: number;
            /** Progress */
            progress: number;
            /** Spi */
            spi: number | null;
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /** Status */
            status: string;
        };
        /** SummaryRead */
        SummaryRead: {
            /**
             * As Of
             * Format: date-time
             * @description Момент анализа, чьи выводы пересказаны
             */
            as_of: string;
            /**
             * Generated By
             * @description `LLM` или `TEMPLATE` — показывать всегда (ADR-0008)
             */
            generated_by: string;
            /**
             * Llm Rejected
             * @description Почему текст нейросети отброшен: числа не из фактов, чужие ID, недоступность
             */
            llm_rejected: string[];
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Period From
             * Format: date
             */
            period_from: string;
            /**
             * Period To
             * Format: date
             */
            period_to: string;
            /**
             * Source
             * @description Откуда текст и почему шаблон, если нейросеть не подошла
             */
            source: string;
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_rules_api_v1_analysis_deviation_rules_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DeviationRuleRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_api_v1_analysis_deviation_rules__code__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviationRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_v1_analysis_deviation_rules__code__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path: {
                code: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviationRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviationRuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deviations_api_v1_analysis_deviations_get: {
        parameters: {
            query?: {
                object_id?: string | null;
                code?: string[];
                severity?: string[];
                status?: string[];
                verdict?: string[];
                stage_id?: string | null;
                area?: string | null;
                from?: string | null;
                to?: string | null;
                sort?: string;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DeviationRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_deviation_api_v1_analysis_deviations__deviation_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                deviation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_verdict_api_v1_analysis_deviations__deviation_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path: {
                deviation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviationVerdict"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_deviation_api_v1_analysis_deviations__deviation_id__explain_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                deviation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_equipment_api_v1_analysis_objects__object_id__equipment_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
            };
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EquipmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_progress_api_v1_analysis_objects__object_id__progress_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_v1_analysis_objects__object_id__status_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectStatusRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reports_api_v1_analysis_reports_get: {
        parameters: {
            query: {
                object_id: string;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ReportRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_report_api_v1_analysis_reports_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportCreated"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_report_api_v1_analysis_reports__key__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReportRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_v1_analysis_runs_post: {
        parameters: {
            query?: {
                wait?: boolean;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"] | components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_v1_analysis_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_summary_api_v1_analysis_summary_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
