/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/plan/calendars": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Рабочие календари */
        get: operations["list_calendars_api_v1_plan_calendars_get"];
        put?: never;
        /** Создать календарь */
        post: operations["create_calendar_api_v1_plan_calendars_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/calendars/{calendar_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Календарь */
        get: operations["get_calendar_api_v1_plan_calendars__calendar_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить календарь
         * @description Выходные, праздники, рабочие часы или часовой пояс: у всех объектов на календаре растёт `plan_version`, и в analysis уходит сигнал «пересчитай».
         */
        patch: operations["update_calendar_api_v1_plan_calendars__calendar_id__patch"];
        trace?: never;
    };
    "/api/v1/plan/equipment-classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Классы техники
         * @description Новый класс — запись в `packages/contracts/equipment_classes.yaml` и перезапуск plan-service и vision-service, без правки кода.
         */
        get: operations["get_equipment_classes_api_v1_plan_equipment_classes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/objects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Список объектов */
        get: operations["list_objects_api_v1_plan_objects_get"];
        put?: never;
        /** Создать объект */
        post: operations["create_object_api_v1_plan_objects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/objects/{object_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Карточка объекта */
        get: operations["get_object_api_v1_plan_objects__object_id__get"];
        put?: never;
        post?: never;
        /** Перевести объект в архив */
        delete: operations["archive_object_api_v1_plan_objects__object_id__delete"];
        options?: never;
        head?: never;
        /** Изменить реквизиты объекта */
        patch: operations["update_object_api_v1_plan_objects__object_id__patch"];
        trace?: never;
    };
    "/api/v1/plan/objects/{object_id}/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Весь план объекта
         * @description Этапы по `seq`, связи, правила, календарь и классы техники одним ответом. Объект без этапов — не ошибка: `stages: []`. Выключенное правило приходит как `rule: null`.
         */
        get: operations["get_plan_api_v1_plan_objects__object_id__plan_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/objects/{object_id}/plan/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Сгенерировать график по МРР-3.2.81-12
         * @description Сроки периодов — табл. 1 п. 5.1.21 с интерполяцией и коэффициентами, этапы и правила — из шаблона типа объекта, даты — по календарю объекта. У каждого этапа в `basis` — откуда его срок. Поверх существующего графика — только с `force=true` (ручные правки затираются). Нет норм для типа или параметры вне таблицы — `NORMS_NOT_AVAILABLE`, график тогда импортируется из файла.
         */
        post: operations["generate_plan_api_v1_plan_objects__object_id__plan_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/objects/{object_id}/plan/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Импорт графика из CSV или XLSX
         * @description Столбцы: код, наименование, начало, окончание (обязательно); тип участка, визуальная стадия, связи (`12.3.1 FS+2`, несколько — через запятую), фаза. Недостающее берётся из шаблона этапа с тем же кодом, вместе с правилом «этап → техника». График заменяется целиком; поверх существующего — только с `force=true`. Ошибки — `PLAN_IMPORT_INVALID` со списком `details.errors` (строка, столбец, текст).
         */
        post: operations["import_plan_api_v1_plan_objects__object_id__plan_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/objects/{object_id}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Этапы объекта
         * @description Этапы по `seq` вместе с правилом «этап → техника» (`rule`, `null` — правила нет).
         */
        get: operations["list_stages_api_v1_plan_objects__object_id__stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Правила этапов */
        get: operations["list_rules_api_v1_plan_rules_get"];
        put?: never;
        /**
         * Создать правило этапа
         * @description Коды классов проверяются по `equipment_classes.yaml`. Версия правила и `plan_version` объекта растут, в analysis уходит сигнал «пересчитай». `X-Actor` — кто правит, в журнал.
         */
        post: operations["create_rule_api_v1_plan_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Правило этапа */
        get: operations["get_rule_api_v1_plan_rules__rule_id__get"];
        put?: never;
        post?: never;
        /**
         * Удалить правило этапа
         * @description По этапу без правила не проверяются D1, D2, D8, D9. `plan_version` растёт.
         */
        delete: operations["delete_rule_api_v1_plan_rules__rule_id__delete"];
        options?: never;
        head?: never;
        /**
         * Изменить правило этапа
         * @description Коды классов проверяются по `equipment_classes.yaml`. Версия правила и `plan_version` объекта растут, в analysis уходит сигнал «пересчитай». `X-Actor` — кто правит, в журнал.
         */
        patch: operations["update_rule_api_v1_plan_rules__rule_id__patch"];
        trace?: never;
    };
    "/api/v1/plan/stages/{stage_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Изменить этап
         * @description Даты (включительно), тип участка, нормативная длительность, стадия по фото, отметка «этап выполнен» (`completed_on`, `completion_note`; автор — из `X-Actor`, `completed_on: null` снимает отметку). `plan_version` объекта растёт, в analysis уходит сигнал «пересчитай».
         */
        patch: operations["update_stage_api_v1_plan_stages__stage_id__patch"];
        trace?: never;
    };
    "/api/v1/plan/work-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Справочник работ
         * @description В порядке файла заказчика: «10.2» раньше «10.10», строки без кода — сразу за своим кодом.
         */
        get: operations["list_work_types_api_v1_plan_work_types_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plan/work-types/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузить справочник работ из XLSX
         * @description «Сводный перечень строительных работ ЛТЦ» (data/README.md). Коды, которые Excel превратил в даты, восстанавливаются (`d.m.2025` → `d.m`), строки без кода относятся к 4-му уровню ближайшего кода сверху. Справочник заменяется целиком. Ошибки — `WORK_TYPES_IMPORT_INVALID` со списком `details.errors` (строка, столбец, текст).
         */
        post: operations["import_work_types_api_v1_plan_work_types_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Процесс жив */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Готов обслуживать запросы */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_plan_api_v1_plan_objects__object_id__plan_import_post */
        Body_import_plan_api_v1_plan_objects__object_id__plan_import_post: {
            /**
             * File
             * Format: binary
             * @description График: .csv (UTF-8 или cp1251) или .xlsx
             */
            file: string;
        };
        /** Body_import_work_types_api_v1_plan_work_types_import_post */
        Body_import_work_types_api_v1_plan_work_types_import_post: {
            /**
             * File
             * Format: binary
             * @description Справочник работ, .xlsx, первый лист
             */
            file: string;
        };
        /** CalendarCreate */
        CalendarCreate: {
            /**
             * Code
             * @description Не меняется после создания: на код ссылается DEFAULT_CALENDAR
             * @example moscow-5day
             */
            code: string;
            /**
             * Holidays
             * @description Нерабочие праздничные дни; у каждой даты — источник
             */
            holidays?: string[];
            /** Name */
            name: string;
            /**
             * Timezone
             * @description IANA, например Europe/Moscow
             * @default Europe/Moscow
             */
            timezone: string;
            /**
             * Weekend Days
             * @description Выходные по ISO: понедельник = 1, воскресенье = 7
             */
            weekend_days: number[];
            work_hours: components["schemas"]["WorkHours"];
        };
        /** CalendarRead */
        CalendarRead: {
            /** Code */
            code: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Holidays */
            holidays: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Timezone */
            timezone: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Weekend Days */
            weekend_days: number[];
            work_hours: components["schemas"]["WorkHours"];
        };
        /**
         * CalendarUpdate
         * @description Частичное изменение. Списки заменяются целиком: праздник убирается новым списком.
         */
        CalendarUpdate: {
            /** Holidays */
            holidays?: string[] | null;
            /** Name */
            name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Weekend Days */
            weekend_days?: number[] | null;
            work_hours?: components["schemas"]["WorkHours"] | null;
        };
        /** EquipmentClassRead */
        EquipmentClassRead: {
            /**
             * Aliases
             * @description Метки класса во внешних датасетах
             */
            aliases: string[];
            /**
             * Code
             * @example excavator
             */
            code: string;
            /** Group */
            group: string;
            /** Name Ru */
            name_ru: string;
            /**
             * Prompts
             * @description Текстовые запросы детектору
             */
            prompts: string[];
            /**
             * Transient
             * @description Приезжает рейсами: присутствие считается за окно нескольких сессий
             */
            transient: boolean;
            /**
             * Works In Place
             * @description Работает, не сдвигаясь с места: неподвижность на рабочем участке не простой
             */
            works_in_place: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * ObjectCreate
         * @description Создание объекта.
         *
         *     Тип можно не указывать: по умолчанию объект — монолитный жилой дом.
         */
        ObjectCreate: {
            /** Address */
            address?: string | null;
            /**
             * Name
             * @example Строительство монолитного жилого дома 17 этажей, г. Москва
             */
            name: string;
            /** Object Type */
            object_type?: ("RESIDENTIAL_MONOLITH" | "RESIDENTIAL_PANEL" | "PUBLIC_BUILDING" | "ROAD") | null;
            /**
             * Plan Start
             * @description Плановая дата начала СМР
             */
            plan_start?: string | null;
            /**
             * Tep
             * @description Параметры для генератора графика: этажность, площадь, секции, сваи, сменность
             */
            tep?: Record<string, never>;
        };
        /** ObjectRead */
        ObjectRead: {
            /** Address */
            address: string | null;
            /**
             * Calendar Id
             * @description Рабочий календарь; при создании — DEFAULT_CALENDAR
             */
            calendar_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Object Type
             * @enum {string}
             */
            object_type: "RESIDENTIAL_MONOLITH" | "RESIDENTIAL_PANEL" | "PUBLIC_BUILDING" | "ROAD";
            /** Plan Start */
            plan_start: string | null;
            /**
             * Plan Version
             * @description Растёт при любой правке этапов, правил или календаря; 0 — план не заводился
             */
            plan_version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "DRAFT" | "ACTIVE" | "ARCHIVED";
            /** Tep */
            tep: Record<string, never>;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * ObjectUpdate
         * @description Частичное изменение: передаются только меняемые поля.
         */
        ObjectUpdate: {
            /** Address */
            address?: string | null;
            /** Name */
            name?: string | null;
            /** Object Type */
            object_type?: ("RESIDENTIAL_MONOLITH" | "RESIDENTIAL_PANEL" | "PUBLIC_BUILDING" | "ROAD") | null;
            /** Plan Start */
            plan_start?: string | null;
            /** Status */
            status?: ("DRAFT" | "ACTIVE" | "ARCHIVED") | null;
            /** Tep */
            tep?: Record<string, never> | null;
        };
        /** Page[CalendarRead] */
        Page_CalendarRead_: {
            /** Items */
            items: components["schemas"]["CalendarRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[EquipmentClassRead] */
        Page_EquipmentClassRead_: {
            /** Items */
            items: components["schemas"]["EquipmentClassRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[ObjectRead] */
        Page_ObjectRead_: {
            /** Items */
            items: components["schemas"]["ObjectRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[RuleRead] */
        Page_RuleRead_: {
            /** Items */
            items: components["schemas"]["RuleRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[StageRead] */
        Page_StageRead_: {
            /** Items */
            items: components["schemas"]["StageRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[WorkTypeRead] */
        Page_WorkTypeRead_: {
            /** Items */
            items: components["schemas"]["WorkTypeRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Plan */
        Plan: {
            calendar: components["schemas"]["PlanCalendar"];
            /** Equipment Classes */
            equipment_classes: components["schemas"]["PlanEquipmentClass"][];
            object: components["schemas"]["PlanObject"];
            /** Plan Version */
            plan_version: number;
            /**
             * Stages
             * @description Все этапы объекта по seq
             */
            stages: components["schemas"]["PlanStage"][];
        };
        /** PlanCalendar */
        PlanCalendar: {
            /** Code */
            code: string;
            /** Holidays */
            holidays: string[];
            /** Timezone */
            timezone: string;
            /** Weekend Days */
            weekend_days: number[];
            work_hours: components["schemas"]["WorkHours"];
        };
        /** PlanEquipmentClass */
        PlanEquipmentClass: {
            /** Code */
            code: string;
            /**
             * Group
             * @enum {string}
             */
            group: "EARTHWORKS" | "LIFTING" | "CONCRETE" | "TRANSPORT" | "ROAD" | "OTHER";
            /** Name Ru */
            name_ru: string;
            /** Transient */
            transient: boolean;
            /** Works In Place */
            works_in_place: boolean;
        };
        /**
         * PlanGenerateRequest
         * @description Всё необязательно: чего нет в запросе, берётся из карточки объекта.
         */
        PlanGenerateRequest: {
            /**
             * Start Date
             * @description Дата начала; по умолчанию `plan_start` объекта. Сохраняется в нём
             */
            start_date?: string | null;
            /**
             * Tep
             * @description Параметры: `floors`, `total_area` (м² квартир) — обязательно; `sections`, `piles`, `shifts` (`1.5`, `2`, `3`). Дополняют `tep` объекта и сохраняются в нём
             * @example {
             *       "floors": 17,
             *       "piles": 200,
             *       "sections": 2,
             *       "total_area": 10000
             *     }
             */
            tep?: Record<string, never> | null;
        };
        /** PlanGenerateResult */
        PlanGenerateResult: {
            /**
             * Basis
             * @description Откуда срок: пункт и строка таблицы МРР, коэффициенты
             */
            basis: string;
            /**
             * Critical Stages
             * @description Сколько этапов на критическом пути
             */
            critical_stages: number;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Plan End
             * Format: date
             * @description Последний рабочий день графика
             */
            plan_end: string;
            /**
             * Plan Start
             * Format: date
             * @description Первый рабочий день графика
             */
            plan_start: string;
            /** Plan Version */
            plan_version: number;
            /**
             * Rules
             * @description Сколько этапов получили правило из шаблона
             */
            rules: number;
            /**
             * Stages
             * @description Сколько этапов в новом графике
             */
            stages: number;
            /**
             * Total Months
             * @description Срок по МРР с коэффициентами, мес.
             */
            total_months: number;
        };
        /** PlanImportResult */
        PlanImportResult: {
            /**
             * Critical Stages
             * @description Сколько этапов на критическом пути
             */
            critical_stages: number;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Plan Version */
            plan_version: number;
            /**
             * Rules
             * @description Сколько этапов получили правило из шаблона
             */
            rules: number;
            /**
             * Stages
             * @description Сколько этапов в новом графике
             */
            stages: number;
        };
        /** PlanObject */
        PlanObject: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Object Type
             * @enum {string}
             */
            object_type: "RESIDENTIAL_MONOLITH" | "RESIDENTIAL_PANEL" | "PUBLIC_BUILDING" | "ROAD";
            /** Plan Start */
            plan_start: string | null;
        };
        /** PlanRule */
        PlanRule: {
            /** Allowed */
            allowed: string[];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Min Sessions */
            min_sessions: number;
            /** Required */
            required: components["schemas"]["RequiredGroup"][];
            signature: components["schemas"]["Signature"];
            /** Version */
            version: number;
        };
        /** PlanStage */
        PlanStage: {
            /** Basis */
            basis: string | null;
            /** Code */
            code: string;
            /** Completed By */
            completed_by?: string | null;
            /**
             * Completed On
             * @description Отметка оператора «этап выполнен» — последний день работ, включительно; как её учитывает анализ — methodology.md, 10.3b
             */
            completed_on?: string | null;
            /** Completion Note */
            completion_note?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Critical */
            is_critical: boolean;
            /** Name */
            name: string;
            /** Norm Duration Days */
            norm_duration_days: number;
            /**
             * Phase
             * @enum {string}
             */
            phase: "PREPARATORY" | "SUBSTRUCTURE" | "SUPERSTRUCTURE" | "ENVELOPE_ROOF" | "NETWORKS" | "LANDSCAPING";
            /**
             * Plan End
             * Format: date
             * @description Последний рабочий день этапа, включительно
             */
            plan_end: string;
            /**
             * Plan Start
             * Format: date
             */
            plan_start: string;
            /** Predecessors */
            predecessors: components["schemas"]["PredecessorRead"][];
            /** @description null — правила нет или оно выключено: D1, D2, D8, D9 по этапу не проверяются */
            rule?: components["schemas"]["PlanRule"] | null;
            /** Seq */
            seq: number;
            /** Total Float Days */
            total_float_days: number;
            /** Visual Stage */
            visual_stage: ("PIT" | "PILES" | "FOUNDATION" | "FRAME" | "FACADE" | "LANDSCAPING") | null;
            /** Work Codes */
            work_codes: string[];
            /**
             * Zone Type
             * @enum {string}
             */
            zone_type: "PIT" | "BUILDING_FOOTPRINT" | "PERIMETER" | "ENTRY_GATE" | "STORAGE" | "DANGER" | "ROAD";
        };
        /** PredecessorRead */
        PredecessorRead: {
            /**
             * Lag Days
             * @description Лаг в рабочих днях
             */
            lag_days: number;
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "FS" | "SS" | "FF" | "SF";
        };
        /**
         * RequiredGroup
         * @description Группа «любой из»: выполнена, если суммарно единиц классов не меньше min.
         */
        RequiredGroup: {
            /**
             * Any Of
             * @example [
             *       "roller",
             *       "bulldozer"
             *     ]
             */
            any_of: string[];
            /** Min */
            min: number;
        };
        /** RestoredCode */
        RestoredCode: {
            /**
             * Cell
             * @description Дата, которую Excel записал вместо кода
             */
            cell: string;
            /** Code */
            code: string;
            /**
             * Row
             * @description Строка файла, как в Excel
             */
            row: number;
        };
        /** RuleCreate */
        RuleCreate: {
            /**
             * Allowed
             * @description Не вызывает D3
             */
            allowed?: string[];
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Min Sessions
             * @description Сколько рабочих сессий подряд держится условие; по умолчанию 2
             */
            min_sessions?: number | null;
            /** Required */
            required?: components["schemas"]["RequiredGroup"][];
            signature?: components["schemas"]["Signature"];
            /**
             * Stage Id
             * Format: uuid
             * @description У этапа не больше одного правила
             */
            stage_id: string;
        };
        /** RuleRead */
        RuleRead: {
            /** Allowed */
            allowed: string[];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Min Sessions */
            min_sessions: number;
            /** Required */
            required: components["schemas"]["RequiredGroup"][];
            signature: components["schemas"]["Signature"];
            /**
             * Stage Id
             * Format: uuid
             */
            stage_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Version
             * @description Растёт при каждой правке; попадает в отклонение
             */
            version: number;
        };
        /**
         * RuleUpdate
         * @description Частичное изменение. Списки и сигнатура заменяются целиком.
         */
        RuleUpdate: {
            /** Allowed */
            allowed?: string[] | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Min Sessions */
            min_sessions?: number | null;
            /** Required */
            required?: components["schemas"]["RequiredGroup"][] | null;
            signature?: components["schemas"]["Signature"] | null;
        };
        /**
         * Signature
         * @description Признак фактического старта этапа: техника одновременно и (или) стадия по фото.
         */
        Signature: {
            /** Equipment */
            equipment?: string[];
            /**
             * Stage Label
             * @description Стадия по фото не раньше
             */
            stage_label?: ("PIT" | "PILES" | "FOUNDATION" | "FRAME" | "FACADE" | "LANDSCAPING") | null;
        };
        /** StageRead */
        StageRead: {
            /** Basis */
            basis: string | null;
            /** Code */
            code: string;
            /**
             * Completed By
             * @description Кто поставил отметку
             */
            completed_by?: string | null;
            /**
             * Completed On
             * @description Отметка «этап выполнен»: последний день работ (ADR-0015)
             */
            completed_on?: string | null;
            /**
             * Completion Note
             * @description Комментарий к отметке
             */
            completion_note?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Critical */
            is_critical: boolean;
            /** Name */
            name: string;
            /** Norm Duration Days */
            norm_duration_days: number;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Phase
             * @enum {string}
             */
            phase: "PREPARATORY" | "SUBSTRUCTURE" | "SUPERSTRUCTURE" | "ENVELOPE_ROOF" | "NETWORKS" | "LANDSCAPING";
            /**
             * Plan End
             * Format: date
             * @description Последний рабочий день этапа, включительно
             */
            plan_end: string;
            /**
             * Plan Start
             * Format: date
             */
            plan_start: string;
            /** Predecessors */
            predecessors: components["schemas"]["PredecessorRead"][];
            /** @description Правило «этап → техника» */
            rule?: components["schemas"]["RuleRead"] | null;
            /** Seq */
            seq: number;
            /**
             * Source
             * @enum {string}
             */
            source: "GENERATED" | "IMPORT" | "MANUAL";
            /** Total Float Days */
            total_float_days: number;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Visual Stage */
            visual_stage: ("PIT" | "PILES" | "FOUNDATION" | "FRAME" | "FACADE" | "LANDSCAPING") | null;
            /** Work Codes */
            work_codes: string[];
            /**
             * Zone Type
             * @enum {string}
             */
            zone_type: "PIT" | "BUILDING_FOOTPRINT" | "PERIMETER" | "ENTRY_GATE" | "STORAGE" | "DANGER" | "ROAD";
        };
        /**
         * StageUpdate
         * @description Частичное изменение. Связи здесь не правятся, критический путь пересчитывается.
         */
        StageUpdate: {
            /**
             * Completed On
             * @description Отметка «этап выполнен» — последний день работ; автор — из `X-Actor`. null — снять отметку вместе с автором и комментарием
             */
            completed_on?: string | null;
            /**
             * Completion Note
             * @description Комментарий к отметке: акт, кто принял
             */
            completion_note?: string | null;
            /**
             * Norm Duration Days
             * @description Нормативная длительность в рабочих днях
             */
            norm_duration_days?: number | null;
            /**
             * Plan End
             * @description Включительно
             */
            plan_end?: string | null;
            /** Plan Start */
            plan_start?: string | null;
            /**
             * Visual Stage
             * @description null — снять стадию
             */
            visual_stage?: ("PIT" | "PILES" | "FOUNDATION" | "FRAME" | "FACADE" | "LANDSCAPING") | null;
            /**
             * Zone Type
             * @description Только тип с ролью WORK
             */
            zone_type?: ("PIT" | "BUILDING_FOOTPRINT" | "PERIMETER" | "ENTRY_GATE" | "STORAGE" | "DANGER" | "ROAD") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkHours */
        WorkHours: {
            /**
             * End
             * @example 23:00
             */
            end: string;
            /**
             * Start
             * @example 07:00
             */
            start: string;
        };
        /** WorkTypeImportResult */
        WorkTypeImportResult: {
            /**
             * Restored Codes
             * @description Коды, которые Excel превратил в даты, и во что они восстановлены
             */
            restored_codes: components["schemas"]["RestoredCode"][];
            /**
             * Rows Without Code
             * @description Сколько строк получили код от парсера
             */
            rows_without_code: number;
            /**
             * Work Types
             * @description Сколько строк справочника загружено
             */
            work_types: number;
        };
        /** WorkTypeRead */
        WorkTypeRead: {
            /**
             * Applicable
             * @description Отметки обязательности по столбцам типов объектов файла. `false` не запрещает работу для этого типа (ТЗ, п. 1)
             */
            applicable: {
                [key: string]: boolean;
            };
            /**
             * Code
             * @description Код из файла заказчика. У строки без кода — `<код родителя>/<n>`: n-я такая строка под ближайшим кодом сверху
             * @example 12.3.1
             */
            code: string;
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Parent Code */
            parent_code: string | null;
            /**
             * Source
             * @description Файл, лист и номер строки первоисточника
             */
            source: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_calendars_api_v1_plan_calendars_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CalendarRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_calendar_api_v1_plan_calendars_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_api_v1_plan_calendars__calendar_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                calendar_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_calendar_api_v1_plan_calendars__calendar_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                calendar_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CalendarUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalendarRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_equipment_classes_api_v1_plan_equipment_classes_get: {
        parameters: {
            query?: {
                group?: ("EARTHWORKS" | "LIFTING" | "CONCRETE" | "TRANSPORT" | "ROAD" | "OTHER") | null;
                transient?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EquipmentClassRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_objects_api_v1_plan_objects_get: {
        parameters: {
            query?: {
                status?: ("DRAFT" | "ACTIVE" | "ARCHIVED") | null;
                object_type?: ("RESIDENTIAL_MONOLITH" | "RESIDENTIAL_PANEL" | "PUBLIC_BUILDING" | "ROAD") | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ObjectRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_object_api_v1_plan_objects_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_object_api_v1_plan_objects__object_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_object_api_v1_plan_objects__object_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_object_api_v1_plan_objects__object_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ObjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_plan_api_v1_plan_objects__object_id__plan_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_plan_api_v1_plan_objects__object_id__plan_generate_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PlanGenerateRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanGenerateResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_plan_api_v1_plan_objects__object_id__plan_import_post: {
        parameters: {
            query?: {
                force?: boolean;
            };
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_plan_api_v1_plan_objects__object_id__plan_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_stages_api_v1_plan_objects__object_id__stages_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_StageRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_api_v1_plan_rules_get: {
        parameters: {
            query?: {
                stage_id?: string | null;
                object_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_RuleRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_api_v1_plan_rules_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rule_api_v1_plan_rules__rule_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_api_v1_plan_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rule_api_v1_plan_rules__rule_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stage_api_v1_plan_stages__stage_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path: {
                stage_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StageUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_work_types_api_v1_plan_work_types_get: {
        parameters: {
            query?: {
                level?: number | null;
                parent_code?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_WorkTypeRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_work_types_api_v1_plan_work_types_import_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
                "X-Actor"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_work_types_api_v1_plan_work_types_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkTypeImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
