/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/site/cameras": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Камеры */
        get: operations["list_cameras_api_v1_site_cameras_get"];
        put?: never;
        /**
         * Завести камеру
         * @description Код в объекте не повторяется (`CAMERA_ALREADY_EXISTS`). При загрузке папки снимков камеры заводятся сами по именам подпапок.
         */
        post: operations["create_camera_api_v1_site_cameras_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/cameras/{camera_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Камера */
        get: operations["get_camera_api_v1_site_cameras__camera_id__get"];
        put?: never;
        post?: never;
        /**
         * Деактивировать камеру
         * @description Камера и её зоны не удаляются: на них ссылаются снимки и детекции.
         */
        delete: operations["delete_camera_api_v1_site_cameras__camera_id__delete"];
        options?: never;
        head?: never;
        /**
         * Изменить камеру
         * @description Название, эталонный кадр (снимок этой камеры), параметры установки, активность. `is_active: false` деактивирует и зоны камеры; смена активности пересчитывает факты окон объекта в фоне.
         */
        patch: operations["update_camera_api_v1_site_cameras__camera_id__patch"];
        trace?: never;
    };
    "/api/v1/site/images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Снимки
         * @description По времени съёмки; снимки без времени — в конце. `from` и `to` — полуинтервал по `captured_at` (ISO-8601).
         */
        get: operations["list_images_api_v1_site_images_get"];
        put?: never;
        /**
         * Загрузить снимки пакетом
         * @description До 200 файлов (поле `files`), каждый до `MAX_IMAGE_MB`. Камера — поле `camera_code`, иначе подпапка в имени файла (`cam-north/20261020_090000.jpg`); новая камера заводится сама. Время: EXIF → дата и время в имени файла → поле `captured_at` (ISO-8601; без смещения — местное время камеры, `CAMERA_TIMEZONE`). Без времени снимок принимается со статусом `NEEDS_TIME`. Первый снимок камеры становится её эталонным кадром. Ответ — частичный успех: `accepted` и `rejected`.
         */
        post: operations["upload_images_api_v1_site_images_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/images/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Импорт снимков из смонтированной папки
         * @description Папка `IMPORT_DIR/<path>`: подпапка — код камеры (`cam-north/...`), камеры заводятся сами, скрытые файлы пропускаются. Время: EXIF → дата и время в имени файла → поле `captured_at` (ISO-8601; без смещения — местное время камеры, `CAMERA_TIMEZONE`). Без времени снимок принимается со статусом `NEEDS_TIME`. Первый снимок камеры становится её эталонным кадром. Повторный импорт той же папки отклоняет уже загруженные снимки как `IMAGE_ALREADY_EXISTS`.
         */
        post: operations["import_images_api_v1_site_images_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/images/reanalyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Распознать снимки объекта заново
         * @description После смены модели или её порога: распознанные (`ANALYZED`) и отказные (`FAILED`) снимки объекта — или одной камеры — снова получают `PENDING` и распознаются воркером; факты окон пересчитываются по мере распознавания. Пока идёт повтор, `pending_images` в фактах больше нуля.
         */
        post: operations["reanalyze_images_api_v1_site_images_reanalyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/images/{image_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Снимок
         * @description Метаданные, ссылка для браузера (путь на gateway), рамки техники с точкой контакта и зоной, стадия по снимку. `link=internal` — ссылка на внутренний адрес хранилища (`S3_ENDPOINT`) для других сервисов: так снимки берёт отчёт analysis (interservice.md, контракт 6).
         */
        get: operations["get_image_api_v1_site_images__image_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Указать время съёмки вручную
         * @description Только для статуса `NEEDS_TIME` (`IMAGE_TIME_ALREADY_SET` иначе). Снимок получает окно наблюдения и статус `PENDING`, источник времени — `MANUAL`.
         */
        patch: operations["set_image_time_api_v1_site_images__image_id__patch"];
        trace?: never;
    };
    "/api/v1/site/objects/{object_id}/areas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Участки объекта
         * @description Участок — активные зоны активных камер с одинаковыми типом и названием, ключ `ТИП:Название` (ADR-0013). Плюс `zones_version` объекта.
         */
        get: operations["get_areas_api_v1_site_objects__object_id__areas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/objects/{object_id}/facts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Факты за период
         * @description Межсервисный контракт (interservice.md, раздел 2): окна с распознанными снимками, участки × классы техники (максимум по камерам), видимость участков, стадия по фото. Полуинтервал `[from, to)` по началу окна, ISO-8601 UTC. Нет снимков — `sessions: []`; `from >= to` — `INVALID_PERIOD`.
         */
        get: operations["get_facts_api_v1_site_objects__object_id__facts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Окна наблюдения
         * @description Сколько снимков и камер в окне, стадия по фото. Полуинтервал `[from, to)` по началу окна, ISO-8601 UTC.
         */
        get: operations["list_sessions_api_v1_site_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Окно наблюдения
         * @description Камеры окна и пригодность их кадров, факт окна в форме контракта, все снимки окна в любом статусе.
         */
        get: operations["get_session_api_v1_site_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/zones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Зоны */
        get: operations["list_zones_api_v1_site_zones_get"];
        put?: never;
        /**
         * Создать зону
         * @description Полигон в долях 0…1 от размера кадра, без самопересечений (`INVALID_POLYGON`). Название по умолчанию — название типа из enums.yaml.
         */
        post: operations["create_zone_api_v1_site_zones_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/zones/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Загрузить камеры и зоны из cameras.json
         * @description Формат `data/seed/cameras.json` плюс `object_id`. Камеры сверяются по коду, зоны камеры — по подписи участка: новые создаются, изменённые получают новый полигон, отсутствующие в файле деактивируются. Повторный импорт того же файла ничего не меняет. Ошибки полигонов — по всему файлу, с путём (`INVALID_POLYGON`, `details.errors`). Если разметка поменялась, факты окон объекта пересчитываются в фоне.
         */
        post: operations["import_zones_api_v1_site_zones_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/zones/reapply": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Пересчитать факты по текущим зонам
         * @description Заново отнести детекции объекта к активным зонам и пересчитать факты всех его окон — без повторного распознавания; затем сигнал в analysis. Правки зон и камер ставят этот пересчёт сами; вручную он нужен, если очередь была недоступна (`QUEUE_UNAVAILABLE`).
         */
        post: operations["reapply_zones_api_v1_site_zones_reapply_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/site/zones/{zone_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Зона */
        get: operations["get_zone_api_v1_site_zones__zone_id__get"];
        put?: never;
        post?: never;
        /**
         * Деактивировать зону
         * @description Зона не удаляется: на неё ссылаются детекции. Версия зоны растёт, вместе с ней — `zones_version` объекта; факты окон объекта пересчитываются в фоне без повторного распознавания.
         */
        delete: operations["delete_zone_api_v1_site_zones__zone_id__delete"];
        options?: never;
        head?: never;
        /**
         * Изменить зону
         * @description Версия зоны растёт, вместе с ней — `zones_version` объекта; факты окон объекта пересчитываются в фоне без повторного распознавания.
         */
        patch: operations["update_zone_api_v1_site_zones__zone_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Процесс жив */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Готов обслуживать запросы */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcceptedImage */
        AcceptedImage: {
            /** Camera Code */
            camera_code: string;
            /**
             * Captured At
             * @description UTC; null — ждёт ручного ввода
             */
            captured_at: string | null;
            /**
             * Captured At Source
             * @description EXIF, FILENAME, MANUAL или UNKNOWN
             */
            captured_at_source: string;
            /** File */
            file: string;
            /**
             * Image Id
             * Format: uuid
             */
            image_id: string;
            /**
             * Status
             * @description PENDING — ждёт распознавания, NEEDS_TIME — ждёт времени
             */
            status: string;
            /**
             * Time Detail
             * @description Откуда взято время, словами
             */
            time_detail: string;
        };
        /** AreaCamera */
        AreaCamera: {
            /** Camera Code */
            camera_code: string;
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /**
             * Zone Id
             * Format: uuid
             */
            zone_id: string;
        };
        /** AreaFact */
        AreaFact: {
            /**
             * Area
             * @description Ключ участка `ТИП:Название`
             */
            area: string;
            /**
             * Equipment
             * @description Только классы с count > 0
             */
            equipment: components["schemas"]["EquipmentFact"][];
            /** Name */
            name: string;
            visibility: components["schemas"]["Visibility"];
            /** Zone Type */
            zone_type: string;
        };
        /** AreaRead */
        AreaRead: {
            /**
             * Area
             * @description Ключ участка `ТИП:Название`
             */
            area: string;
            /**
             * Cameras
             * @description Активные камеры, на которых размечен участок
             */
            cameras: components["schemas"]["AreaCamera"][];
            /** Name */
            name: string;
            /**
             * Role
             * @description Роль типа зоны из enums.yaml: WORK, SERVICE, SAFETY
             */
            role: string;
            /** Zone Type */
            zone_type: string;
        };
        /** Body_upload_images_api_v1_site_images_post */
        Body_upload_images_api_v1_site_images_post: {
            /** Camera Code */
            camera_code?: string | null;
            /**
             * Captured At
             * @description Время съёмки, если его нет в файле
             */
            captured_at?: string | null;
            /**
             * Files
             * @description Снимки: JPEG, PNG, WebP
             */
            files: string[];
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
        };
        /** CameraCreate */
        CameraCreate: {
            /**
             * Code
             * @description Он же имя подпапки при пакетной загрузке; в объекте не повторяется
             * @example cam-north
             */
            code: string;
            /**
             * Install Meta
             * @description Высота подвеса, азимут, ИК-подсветка
             */
            install_meta?: Record<string, never>;
            /**
             * Name
             * @description По умолчанию совпадает с кодом
             */
            name?: string | null;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
        };
        /** CameraFact */
        CameraFact: {
            /** Code */
            code: string;
            /**
             * Image Ids
             * @description Распознанные снимки камеры в окне — доказательство там, где рамок нет (D1)
             */
            image_ids: string[];
            /**
             * Images
             * @description Распознанные снимки камеры в окне
             */
            images: number;
            /**
             * Reason
             * @description DARK, BLURRED, OCCLUDED или NO_IMAGES; null — пригоден
             */
            reason: string | null;
            /**
             * Usable
             * @description Есть ли среди них пригодный кадр
             */
            usable: boolean;
        };
        /** CameraRead */
        CameraRead: {
            /** Code */
            code: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Install Meta */
            install_meta: Record<string, never>;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Reference Image Id */
            reference_image_id: string | null;
        };
        /** CameraState */
        CameraState: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Code */
            code: string;
            /**
             * Image Ids
             * @description Распознанные снимки камеры в окне — доказательство там, где рамок нет (D1)
             */
            image_ids: string[];
            /**
             * Images
             * @description Распознанные снимки камеры в окне
             */
            images: number;
            /**
             * Reason
             * @description DARK, BLURRED, OCCLUDED или NO_IMAGES; null — пригоден
             */
            reason: string | null;
            /**
             * Usable
             * @description Есть ли среди них пригодный кадр
             */
            usable: boolean;
        };
        /**
         * CameraUpdate
         * @description Частичное изменение. Код не меняется: по нему снимки раскладываются по камерам.
         */
        CameraUpdate: {
            /** Install Meta */
            install_meta?: Record<string, never> | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
            /**
             * Reference Image Id
             * @description Эталонный кадр — снимок этой камеры, на нём размечают зоны
             */
            reference_image_id?: string | null;
        };
        /** DetectionRead */
        DetectionRead: {
            /**
             * Anchor
             * @description Точка контакта с землёй — по ней выбрана зона
             */
            anchor: number[];
            /**
             * Bbox
             * @description [x1, y1, x2, y2] в долях 0…1 от размера кадра
             */
            bbox: number[];
            /** Conf */
            conf: number;
            /** Displacement */
            displacement: number | null;
            /** Equipment Class */
            equipment_class: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Model Version */
            model_version: string;
            /** Moved */
            moved: boolean | null;
            /** Zone Id */
            zone_id: string | null;
        };
        /** EquipmentFact */
        EquipmentFact: {
            /**
             * Count
             * @description Максимум по камерам участка, а не сумма
             */
            count: number;
            /** Equipment Class */
            equipment_class: string;
            /**
             * Evidence
             * @description Детекции, на которых стоит число
             */
            evidence: components["schemas"]["Evidence"][];
            /**
             * Static
             * @description Сколько из count не сдвинулись с прошлого окна камеры; null — не с чем сравнить
             */
            static: number | null;
        };
        /** Evidence */
        Evidence: {
            /** Camera */
            camera: string;
            /** Conf */
            conf: number;
            /**
             * Detection Id
             * Format: uuid
             */
            detection_id: string;
            /**
             * Image Id
             * Format: uuid
             */
            image_id: string;
        };
        /** FolderImport */
        FolderImport: {
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Path
             * @description Папка внутри IMPORT_DIR; каждая её подпапка — код камеры. Пусто — сам IMPORT_DIR
             * @default
             * @example
             * @example day1
             */
            path: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageDetail */
        ImageDetail: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Captured At */
            captured_at: string | null;
            /** Captured At Source */
            captured_at_source: string;
            /**
             * Detections
             * @description Рамки техники; пусто до распознавания
             */
            detections: components["schemas"]["DetectionRead"][];
            /** Error */
            error: string | null;
            /** Exif */
            exif: Record<string, never>;
            /** Height */
            height: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Quality
             * @description Яркость и размытость от vision-service
             */
            quality: Record<string, never>;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /**
             * Session Id
             * @description Окно наблюдения; null — пока нет времени
             */
            session_id: string | null;
            /** Source */
            source: string;
            /** @description Стадия объекта по снимку */
            stage: components["schemas"]["StageObservationRead"] | null;
            /** Status */
            status: string;
            /**
             * Url
             * @description Для браузера — путь без хоста под S3_PUBLIC_PATH (`/storage/images/…`), открывается относительно адреса gateway; при link=internal — полная ссылка на S3_ENDPOINT. Живёт S3_PRESIGN_TTL_S
             */
            url: string;
            /**
             * Usable
             * @description Пригоден ли кадр; null — ещё не распознан
             */
            usable: boolean | null;
            /** Usable Reason */
            usable_reason: string | null;
            /** Width */
            width: number | null;
        };
        /** ImageRead */
        ImageRead: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /** Captured At */
            captured_at: string | null;
            /** Captured At Source */
            captured_at_source: string;
            /** Height */
            height: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /**
             * Session Id
             * @description Окно наблюдения; null — пока нет времени
             */
            session_id: string | null;
            /** Source */
            source: string;
            /** Status */
            status: string;
            /**
             * Usable
             * @description Пригоден ли кадр; null — ещё не распознан
             */
            usable: boolean | null;
            /** Usable Reason */
            usable_reason: string | null;
            /** Width */
            width: number | null;
        };
        /** ImageTimeUpdate */
        ImageTimeUpdate: {
            /**
             * Captured At
             * @description ISO-8601; без смещения — местное время камеры (`CAMERA_TIMEZONE`)
             * @example 2026-10-20T12:03:00
             * @example 2026-10-20T09:03:00Z
             */
            captured_at: string;
        };
        /** ImportCamera */
        ImportCamera: {
            /** Code */
            code: string;
            /** Name */
            name?: string | null;
            /**
             * Reference Image
             * @description Путь снимка в папке загрузки. Пока не используется: эталонным кадром становится первый загруженный снимок камеры
             */
            reference_image?: string | null;
            /** Zones */
            zones?: components["schemas"]["ImportZone"][];
        };
        /** ImportZone */
        ImportZone: {
            /** Name */
            name?: string | null;
            /** Polygon */
            polygon: number[][];
            /**
             * Zone Type
             * @enum {string}
             */
            zone_type: "PIT" | "BUILDING_FOOTPRINT" | "PERIMETER" | "ENTRY_GATE" | "STORAGE" | "DANGER" | "ROAD";
        };
        /**
         * IntakeResult
         * @description Частичный успех: отклонённый файл — строка в `rejected`, а не ошибка запроса.
         */
        IntakeResult: {
            /** Accepted */
            accepted: components["schemas"]["AcceptedImage"][];
            /** Rejected */
            rejected: components["schemas"]["RejectedImage"][];
        };
        /** ObjectAreas */
        ObjectAreas: {
            /** Areas */
            areas: components["schemas"]["AreaRead"][];
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Zones Version
             * @description Сумма версий всех зон объекта, включая неактивные: растёт при любой правке
             */
            zones_version: number;
        };
        /** Page[CameraRead] */
        Page_CameraRead_: {
            /** Items */
            items: components["schemas"]["CameraRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[ImageRead] */
        Page_ImageRead_: {
            /** Items */
            items: components["schemas"]["ImageRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[SessionRead] */
        Page_SessionRead_: {
            /** Items */
            items: components["schemas"]["SessionRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /** Page[ZoneRead] */
        Page_ZoneRead_: {
            /** Items */
            items: components["schemas"]["ZoneRead"][];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /**
             * Total
             * @description Всего записей, удовлетворяющих фильтру
             */
            total: number;
        };
        /**
         * PeriodFacts
         * @description Факты за период [from, to) по началу окна: только окна с распознанными снимками.
         */
        PeriodFacts: {
            /**
             * From
             * Format: date-time
             */
            from: string;
            /**
             * Model Versions
             * @description Версии детектора, давшие детекции периода
             */
            model_versions: string[];
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Pending Images
             * @description Ещё не распознанные снимки периода; > 0 — факты неполные
             */
            pending_images: number;
            /** Sessions */
            sessions: components["schemas"]["WindowFact"][];
            /**
             * To
             * Format: date-time
             */
            to: string;
            /**
             * Zones Version
             * @description Счётчик правок зон объекта
             */
            zones_version: number;
        };
        /** ReanalyzeRequest */
        ReanalyzeRequest: {
            /**
             * Camera Id
             * @description Только снимки этой камеры
             */
            camera_id?: string | null;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
        };
        /** ReanalyzeResult */
        ReanalyzeResult: {
            /**
             * Images
             * @description Сколько распознанных и отказных снимков снова в PENDING
             */
            images: number;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
        };
        /** ReapplyQueued */
        ReapplyQueued: {
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /**
             * Queued
             * @description Пересчёт поставлен в очередь site-worker
             */
            queued: boolean;
        };
        /** RejectedImage */
        RejectedImage: {
            /**
             * Code
             * @description IMAGE_ALREADY_EXISTS, IMAGE_TOO_LARGE, UNSUPPORTED_MEDIA_TYPE, CAMERA_REQUIRED, STORAGE_UNAVAILABLE
             */
            code: string;
            /** File */
            file: string;
            /**
             * Image Id
             * @description Для повтора — id уже загруженного
             */
            image_id?: string | null;
            /** Message */
            message: string;
        };
        /**
         * SessionDetail
         * @description Окно целиком: камеры и пригодность кадров, факт окна, все его снимки.
         */
        SessionDetail: {
            /** Areas */
            areas: components["schemas"]["AreaFact"][];
            /** Camera Count */
            camera_count: number;
            /** Cameras */
            cameras: components["schemas"]["CameraState"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Image Count
             * @description Снимки окна в любом статусе
             */
            image_count: number;
            /**
             * Images
             * @description Снимки окна в любом статусе, по времени съёмки
             */
            images: components["schemas"]["ImageRead"][];
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Outside Zones */
            outside_zones: components["schemas"]["EquipmentFact"][];
            /** Stage Conf */
            stage_conf: number | null;
            /** Stage Label */
            stage_label: string | null;
            stage_observation: components["schemas"]["StageFact"] | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** SessionRead */
        SessionRead: {
            /** Camera Count */
            camera_count: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Image Count
             * @description Снимки окна в любом статусе
             */
            image_count: number;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Stage Conf */
            stage_conf: number | null;
            /** Stage Label */
            stage_label: string | null;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** StageFact */
        StageFact: {
            /** Conf */
            conf: number;
            /**
             * Scores
             * @description Сумма уверенности по меткам за окно
             */
            scores: {
                [key: string]: number;
            };
            /** Stage Label */
            stage_label: string;
        };
        /** StageObservationRead */
        StageObservationRead: {
            /** Conf */
            conf: number;
            /** Scores */
            scores: {
                [key: string]: number;
            };
            /** Stage Label */
            stage_label: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Visibility */
        Visibility: {
            /** Cameras Total */
            cameras_total: number;
            /** Cameras Usable */
            cameras_usable: number;
            /**
             * Reason
             * @description Главная причина непригодности для PARTIAL и BLIND
             */
            reason: string | null;
            /**
             * Status
             * @description OK — все камеры участка, PARTIAL — часть, BLIND — ни одна
             */
            status: string;
        };
        /** WindowFact */
        WindowFact: {
            /**
             * Areas
             * @description Все участки объекта, даже пустые и невидимые
             */
            areas: components["schemas"]["AreaFact"][];
            /**
             * Cameras
             * @description Все активные камеры объекта
             */
            cameras: components["schemas"]["CameraFact"][];
            /**
             * Outside Zones
             * @description Детекции вне всех зон
             */
            outside_zones: components["schemas"]["EquipmentFact"][];
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            stage_observation: components["schemas"]["StageFact"] | null;
            /**
             * Updated At
             * Format: date-time
             * @description Когда факт окна пересчитан последний раз
             */
            updated_at: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
            /**
             * Window Start
             * Format: date-time
             */
            window_start: string;
        };
        /** ZoneCreate */
        ZoneCreate: {
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /**
             * Name
             * @description Название участка; по умолчанию — название типа из enums.yaml («Котлован»). Одинаковые тип и название на разных камерах — один участок
             */
            name?: string | null;
            /**
             * Polygon
             * @example [
             *       [
             *         0.09,
             *         0.47
             *       ],
             *       [
             *         0.3,
             *         0.43
             *       ],
             *       [
             *         0.33,
             *         0.68
             *       ],
             *       [
             *         0.08,
             *         0.71
             *       ]
             *     ]
             */
            polygon: number[][];
            /**
             * Zone Type
             * @enum {string}
             */
            zone_type: "PIT" | "BUILDING_FOOTPRINT" | "PERIMETER" | "ENTRY_GATE" | "STORAGE" | "DANGER" | "ROAD";
        };
        /** ZoneRead */
        ZoneRead: {
            /**
             * Area
             * @description Ключ участка `ТИП:Название`
             */
            readonly area: string;
            /**
             * Camera Id
             * Format: uuid
             */
            camera_id: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Name */
            name: string;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Polygon */
            polygon: number[][];
            /** Version */
            version: number;
            /** Zone Type */
            zone_type: string;
        };
        /**
         * ZoneUpdate
         * @description Правка полигона, типа или названия; `is_active: true` возвращает зону. Версия растёт.
         */
        ZoneUpdate: {
            /** Is Active */
            is_active?: boolean | null;
            /** Name */
            name?: string | null;
            /** Polygon */
            polygon?: number[][] | null;
            /** Zone Type */
            zone_type?: ("PIT" | "BUILDING_FOOTPRINT" | "PERIMETER" | "ENTRY_GATE" | "STORAGE" | "DANGER" | "ROAD") | null;
        };
        /**
         * ZonesImport
         * @description Формат `data/seed/cameras.json` (data/README.md) плюс объект, к которому он относится.
         */
        ZonesImport: {
            /** Cameras */
            cameras: components["schemas"]["ImportCamera"][];
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
        };
        /** ZonesImportResult */
        ZonesImportResult: {
            /** Areas */
            areas: components["schemas"]["AreaRead"][];
            /** Cameras Created */
            cameras_created: number;
            /** Cameras Updated */
            cameras_updated: number;
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
            /** Zones Created */
            zones_created: number;
            /** Zones Deactivated */
            zones_deactivated: number;
            /** Zones Unchanged */
            zones_unchanged: number;
            /** Zones Updated */
            zones_updated: number;
            /**
             * Zones Version
             * @description Сумма версий всех зон объекта, включая неактивные: растёт при любой правке
             */
            zones_version: number;
        };
        /** ZonesReapply */
        ZonesReapply: {
            /**
             * Object Id
             * Format: uuid
             */
            object_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_cameras_api_v1_site_cameras_get: {
        parameters: {
            query?: {
                object_id?: string | null;
                is_active?: boolean | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CameraRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_camera_api_v1_site_cameras_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_camera_api_v1_site_cameras__camera_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_camera_api_v1_site_cameras__camera_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_camera_api_v1_site_cameras__camera_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                camera_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CameraUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CameraRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_images_api_v1_site_images_get: {
        parameters: {
            query?: {
                object_id?: string | null;
                camera_id?: string | null;
                from?: string | null;
                to?: string | null;
                status?: ("NEEDS_TIME" | "PENDING" | "PROCESSING" | "ANALYZED" | "FAILED") | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ImageRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_images_api_v1_site_images_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_images_api_v1_site_images_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_images_api_v1_site_images_import_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntakeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reanalyze_images_api_v1_site_images_reanalyze_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReanalyzeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReanalyzeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_image_api_v1_site_images__image_id__get: {
        parameters: {
            query?: {
                link?: "public" | "internal";
            };
            header?: {
                "x-api-key"?: string;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_image_time_api_v1_site_images__image_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                image_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImageTimeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImageRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_areas_api_v1_site_objects__object_id__areas_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ObjectAreas"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_facts_api_v1_site_objects__object_id__facts_get: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: {
                "x-api-key"?: string;
            };
            path: {
                object_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeriodFacts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_api_v1_site_sessions_get: {
        parameters: {
            query?: {
                object_id?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_SessionRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_api_v1_site_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_zones_api_v1_site_zones_get: {
        parameters: {
            query?: {
                object_id?: string | null;
                camera_id?: string | null;
                include_inactive?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_ZoneRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_zone_api_v1_site_zones_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_zones_api_v1_site_zones_import_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZonesImport"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZonesImportResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reapply_zones_api_v1_site_zones_reapply_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZonesReapply"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReapplyQueued"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_zone_api_v1_site_zones__zone_id__get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_zone_api_v1_site_zones__zone_id__delete: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_zone_api_v1_site_zones__zone_id__patch: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path: {
                zone_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ZoneUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ZoneRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
