/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/vision/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Распознать снимок
         * @description Детекция техники, стадия объекта и качество кадра за один вызов. Тело — JSON `{"image_url": ...}` (так вызывает site-worker) или `multipart/form-data` с полем `file` для ручной проверки. Рамки нормированы 0…1. Недоступная ссылка — `UPSTREAM_UNAVAILABLE`.
         */
        post: operations["analyze_api_v1_vision_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vision/model": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Загруженные модели
         * @description Детектор, классификатор стадии, фактическое устройство, версия и словарь классов, пороги детектора. До окончания загрузки — `MODEL_NOT_LOADED`.
         */
        get: operations["model_api_v1_vision_model_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Процесс жив */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Готов обслуживать запросы */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyzeResult */
        AnalyzeResult: {
            /** Detections */
            detections: components["schemas"]["DetectionRead"][];
            image: components["schemas"]["ImageSize"];
            /**
             * Inference Ms
             * @description Время моделей на снимок без скачивания и очереди
             */
            inference_ms: number;
            model: components["schemas"]["ModelInfo"];
            quality: components["schemas"]["QualityRead"];
            /** @description `null` при `VISION_STAGE_ENABLED=false` */
            stage: components["schemas"]["StageRead"] | null;
        };
        /** ClassRead */
        ClassRead: {
            /** Code */
            code: string;
            /** Prompts */
            prompts: string[];
        };
        /** DetectionRead */
        DetectionRead: {
            /**
             * Bbox
             * @description [x1, y1, x2, y2], доли кадра 0…1 от левого верхнего угла
             * @example [
             *       0.41,
             *       0.52,
             *       0.49,
             *       0.63
             *     ]
             */
            bbox: number[];
            /**
             * Conf
             * @description Не ниже `VISION_DET_CONF`
             */
            conf: number;
            /**
             * Equipment Class
             * @description Код из equipment_classes.yaml, включая `person`
             */
            equipment_class: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImageSize */
        ImageSize: {
            /** Height */
            height: number;
            /** Width */
            width: number;
        };
        /** ModelInfo */
        ModelInfo: {
            /**
             * Classes Version
             * @description Первые 8 символов sha256 файла equipment_classes.yaml
             * @example 3f9a1c2e
             */
            classes_version: string;
            /**
             * Detector
             * @example yolov8s-worldv2
             */
            detector: string;
            /**
             * Device
             * @description Фактическое устройство инференса
             * @example cuda
             */
            device: string;
            /**
             * Stage Classifier
             * @description `null` при `VISION_STAGE_ENABLED=false`
             * @example openclip-vit-b32
             */
            stage_classifier: string | null;
        };
        /** ModelRead */
        ModelRead: {
            /**
             * Classes
             * @description Словарь детектора из equipment_classes.yaml
             */
            classes: components["schemas"]["ClassRead"][];
            /**
             * Classes Version
             * @description Первые 8 символов sha256 файла equipment_classes.yaml
             * @example 3f9a1c2e
             */
            classes_version: string;
            /** Det Conf */
            det_conf: number;
            /** Det Imgsz */
            det_imgsz: number;
            /** Det Iou */
            det_iou: number;
            /**
             * Detector
             * @example yolov8s-worldv2
             */
            detector: string;
            /**
             * Device
             * @description Фактическое устройство инференса
             * @example cuda
             */
            device: string;
            /**
             * Stage Classifier
             * @description `null` при `VISION_STAGE_ENABLED=false`
             * @example openclip-vit-b32
             */
            stage_classifier: string | null;
            /** Stage Labels */
            stage_labels: string[];
        };
        /** QualityRead */
        QualityRead: {
            /**
             * Blur
             * @description Размытость кадра, 0…1; больше — хуже
             */
            blur: number;
            /**
             * Brightness
             * @description Средняя яркость кадра, 0…1
             */
            brightness: number;
        };
        /** StageRead */
        StageRead: {
            /** Conf */
            conf: number;
            /**
             * Label
             * @description Значение `stage_label` из enums.yaml
             */
            label: string;
            /**
             * Scores
             * @description Вероятность каждой метки стадии
             */
            scores: {
                [key: string]: number;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_api_v1_vision_analyze_post: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Image Url
                     * @description Ссылка на снимок; site-worker передаёт presigned-ссылку S3
                     * @example http://s3:8333/images/0f3a/cam-north/2026-10-20/9e41.jpg?X-Amz-Signature=…
                     */
                    image_url: string;
                };
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyzeResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    model_api_v1_vision_model_get: {
        parameters: {
            query?: never;
            header?: {
                "x-api-key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
